package missions

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/stizzfer36-del/uclaw/internal/artifacts"
	"github.com/stizzfer36-del/uclaw/internal/audit"
	"github.com/stizzfer36-del/uclaw/internal/config"
	"github.com/stizzfer36-del/uclaw/internal/ids"
	"github.com/stizzfer36-del/uclaw/internal/sqlitepy"
)

type Mission struct { ID string `json:"id"`; Title string `json:"title"`; Status string `json:"status"`; CreatedBy string `json:"created_by"`; AssignedTo string `json:"assigned_to"`; CreatedAt string `json:"created_at"`; UpdatedAt string `json:"updated_at"` }
type Checkpoint struct { ID string `json:"id"`; MissionID string `json:"mission_id"`; Trigger string `json:"trigger"`; CreatedAt string `json:"created_at"`; SnapshotPath string `json:"snapshot_path"` }
type TimelineEvent struct { ID string `json:"id"`; MissionID string `json:"mission_id"`; EventType string `json:"event_type"`; Message string `json:"message"`; CreatedAt string `json:"created_at"` }
type MatrixEntry struct { ID string `json:"id"`; Type string `json:"type"`; Target string `json:"target"`; Command string `json:"command"`; Required bool `json:"required"`; MinCompleteness int `json:"min_completeness"` }
func Start(ctx context.Context, cfg config.Config, title, createdBy, assignedTo string) (Mission, error) { roomID, err:=defaultRoomID(ctx,cfg.DBPath); if err!=nil { return Mission{}, err }; now:=time.Now().UTC().Format(time.RFC3339); m:=Mission{ID:ids.New("mission"),Title:title,Status:"active",CreatedBy:createdBy,AssignedTo:assignedTo,CreatedAt:now,UpdatedAt:now}; if err:=sqlitepy.ExecParams(ctx,cfg.DBPath,`INSERT INTO missions(id, room_id, title, status, created_by, assigned_to, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,m.ID,roomID,m.Title,m.Status,m.CreatedBy,m.AssignedTo,m.CreatedAt,m.UpdatedAt); err!=nil { return Mission{}, err }; if err:=os.MkdirAll(filepath.Join(cfg.MissionsPath,m.ID),0o755); err!=nil { return Mission{}, err }; _ = AppendTimeline(ctx,cfg,m.ID,"mission",fmt.Sprintf("Mission started by %s", createdBy)); _, _ = SaveCheckpoint(ctx,cfg,m.ID,"mission-start"); _ = audit.Write(ctx,cfg.AuditPath,audit.Event{AgentID:createdBy,Action:"mission_start",Target:title,MissionID:m.ID,Outcome:"success",ApprovalRequired:false}); return m,nil }
func List(ctx context.Context, cfg config.Config) ([]Mission, error) { rows, err:=sqlitepy.Query(ctx,cfg.DBPath,`SELECT id, title, status, created_by, assigned_to, created_at, updated_at FROM missions ORDER BY created_at ASC`); if err!=nil { return nil, err }; out:=make([]Mission,0,len(rows)); for _, row := range rows { out=append(out, Mission{ID:sval(row["id"]),Title:sval(row["title"]),Status:sval(row["status"]),CreatedBy:sval(row["created_by"]),AssignedTo:sval(row["assigned_to"]),CreatedAt:sval(row["created_at"]),UpdatedAt:sval(row["updated_at"])}) }; return out,nil }
func Status(ctx context.Context, cfg config.Config, missionID string) (map[string]interface{}, error) { rows, err:=sqlitepy.Query(ctx,cfg.DBPath,`SELECT id, title, status, created_by, assigned_to, created_at, updated_at FROM missions WHERE id = ?`, missionID); if err!=nil { return nil, err }; if len(rows)==0 { return nil, fmt.Errorf("mission %s not found", missionID) }; arts, _ := artifacts.List(ctx,cfg,missionID); queue, _ := ReviewQueue(ctx,cfg); events, _ := Timeline(ctx,cfg,missionID); return map[string]interface{}{"mission":rows[0],"artifacts":arts,"review_queue":queue,"timeline":events}, nil }
func UpdateStatus(ctx context.Context, cfg config.Config, missionID, status string) error { ok, err:=CanTransition(ctx,cfg,missionID,status); if err!=nil { return err }; if !ok { return fmt.Errorf("mission %s cannot transition to %s under current verification state", missionID, status) }; if err:=sqlitepy.ExecParams(ctx,cfg.DBPath,`UPDATE missions SET status = ?, updated_at = ? WHERE id = ?`, status, time.Now().UTC().Format(time.RFC3339), missionID); err!=nil { return err }; if err:=AppendTimeline(ctx,cfg,missionID,"mission-status","Mission status -> "+status); err!=nil { return err }; return audit.Write(ctx,cfg.AuditPath,audit.Event{AgentID:"system",Action:"mission_status_update",Target:status,MissionID:missionID,Outcome:"success",ApprovalRequired:false}) }
func CanTransition(ctx context.Context, cfg config.Config, missionID, status string) (bool, error) { reviewRows, err:=sqlitepy.Query(ctx,cfg.DBPath,`SELECT COUNT(*) AS count FROM review_queue rq JOIN artifacts a ON a.id = rq.artifact_id WHERE a.mission_id = ? AND rq.status = 'open'`, missionID); if err!=nil { return false, err }; openReview:=intVal(reviewRows[0]["count"])>0; artifactRows, err:=sqlitepy.Query(ctx,cfg.DBPath,`SELECT verification_status FROM artifacts WHERE mission_id = ?`, missionID); if err!=nil { return false, err }; allVerified:=len(artifactRows)>0; for _, row := range artifactRows { if sval(row["verification_status"]) != "verified" { allVerified=false; break } }; switch status { case "blocked": return openReview,nil; case "complete": return !openReview && allVerified,nil; case "active": return !openReview,nil; case "failed", "archived": return true,nil; default: return false,nil } }
func SaveMatrix(cfg config.Config, missionID string, entries []MatrixEntry) (string, error) { path:=filepath.Join(cfg.MissionsPath, missionID, "test_matrix.yaml"); var b strings.Builder; b.WriteString("tests:\n"); for _, entry := range entries { fmt.Fprintf(&b,"  - id: %s\n", entry.ID); fmt.Fprintf(&b,"    type: %s\n", entry.Type); fmt.Fprintf(&b,"    target: %s\n", entry.Target); if entry.Command!="" { fmt.Fprintf(&b,"    command: %s\n", entry.Command) }; if entry.MinCompleteness>0 { fmt.Fprintf(&b,"    min_completeness: %d\n", entry.MinCompleteness) }; fmt.Fprintf(&b,"    required: %t\n", entry.Required) }; if err:=os.WriteFile(path, []byte(b.String()), 0o644); err!=nil { return "", err }; _ = audit.Write(context.Background(), cfg.AuditPath, audit.Event{AgentID:"planner",Action:"mission_matrix_save",Target:path,MissionID:missionID,Outcome:"success",ApprovalRequired:false}); return path,nil }
func LoadMatrix(cfg config.Config, missionID string) ([]MatrixEntry, error) { path:=filepath.Join(cfg.MissionsPath, missionID, "test_matrix.yaml"); body, err:=os.ReadFile(path); if err!=nil { return nil, err }; lines:=strings.Split(string(body),"\n"); var entries []MatrixEntry; var cur *MatrixEntry; for _, line := range lines { trim:=strings.TrimSpace(line); if strings.HasPrefix(trim,"- id:") { if cur!=nil { entries=append(entries,*cur) }; cur=&MatrixEntry{ID:strings.TrimSpace(strings.TrimPrefix(trim,"- id:"))}; continue }; if cur==nil || trim=="" || trim=="tests:" { continue }; key, value, ok := strings.Cut(trim,":"); if !ok { continue }; value = strings.TrimSpace(value); switch key { case "type": cur.Type=value; case "target": cur.Target=value; case "command": cur.Command=value; case "required": cur.Required = value=="true"; case "min_completeness": fmt.Sscanf(value,"%d", &cur.MinCompleteness) } }; if cur!=nil { entries=append(entries,*cur) }; return entries,nil }
func ReviewQueue(ctx context.Context, cfg config.Config) ([]map[string]interface{}, error) { return sqlitepy.Query(ctx,cfg.DBPath,`SELECT * FROM review_queue WHERE status = 'open' ORDER BY created_at ASC`) }
func OverrideReview(ctx context.Context, cfg config.Config, artifactID string) error { if err:=sqlitepy.ExecParams(ctx,cfg.DBPath,`UPDATE review_queue SET status = ?, resolved_at = ? WHERE artifact_id = ? AND status = 'open'`, "overridden", time.Now().UTC().Format(time.RFC3339), artifactID); err!=nil { return err }; if err:=sqlitepy.ExecParams(ctx,cfg.DBPath,`UPDATE artifacts SET verification_status = ? WHERE id = ?`, "disputed", artifactID); err!=nil { return err }; return audit.Write(ctx,cfg.AuditPath,audit.Event{AgentID:"operator",Action:"review_override",Target:artifactID,Outcome:"success",ApprovalRequired:true}) }
func SaveCheckpoint(ctx context.Context, cfg config.Config, missionID, trigger string) (Checkpoint, error) { id:=ids.New("chkpt"); path:=filepath.Join(cfg.ChecksPath, missionID, id); if err:=os.MkdirAll(path,0o755); err!=nil { return Checkpoint{}, err }; files:=map[string]string{"world.db":cfg.DBPath,"graph.db":cfg.GraphDBPath,"audit.jsonl":cfg.AuditPath}; for name, src := range files { body, err:=os.ReadFile(src); if err!=nil && !os.IsNotExist(err) { return Checkpoint{}, err }; if err==nil { if err:=os.WriteFile(filepath.Join(path,name), body, 0o644); err!=nil { return Checkpoint{}, err } } }; cp:=Checkpoint{ID:id,MissionID:missionID,Trigger:trigger,CreatedAt:time.Now().UTC().Format(time.RFC3339),SnapshotPath:path}; if err:=sqlitepy.ExecParams(ctx,cfg.DBPath,`INSERT INTO checkpoints(id, mission_id, trigger, created_at, snapshot_path) VALUES (?, ?, ?, ?, ?)`,cp.ID,cp.MissionID,cp.Trigger,cp.CreatedAt,cp.SnapshotPath); err!=nil { return Checkpoint{}, err }; _ = AppendTimeline(ctx,cfg,missionID,"checkpoint","Mission checkpoint saved"); _ = audit.Write(ctx,cfg.AuditPath,audit.Event{AgentID:"system",Action:"checkpoint_save",Target:cp.ID,MissionID:missionID,Outcome:"success",ApprovalRequired:false}); return cp,nil }
func ListCheckpoints(ctx context.Context, cfg config.Config, missionID string) ([]Checkpoint, error) { rows, err:=sqlitepy.Query(ctx,cfg.DBPath,`SELECT id, mission_id, trigger, created_at, snapshot_path FROM checkpoints WHERE mission_id = ? ORDER BY created_at ASC`, missionID); if err!=nil { return nil, err }; out:=make([]Checkpoint,0,len(rows)); for _, row := range rows { out=append(out, Checkpoint{ID:sval(row["id"]),MissionID:sval(row["mission_id"]),Trigger:sval(row["trigger"]),CreatedAt:sval(row["created_at"]),SnapshotPath:sval(row["snapshot_path"])}) }; return out,nil }
func RestoreCheckpoint(ctx context.Context, cfg config.Config, checkpointID string) error { rows, err:=sqlitepy.Query(ctx,cfg.DBPath,`SELECT snapshot_path FROM checkpoints WHERE id = ?`, checkpointID); if err!=nil { return err }; if len(rows)==0 { return fmt.Errorf("checkpoint %s not found", checkpointID) }; path:=sval(rows[0]["snapshot_path"]); for _, pair := range [][2]string{{filepath.Join(path,"world.db"),cfg.DBPath},{filepath.Join(path,"graph.db"),cfg.GraphDBPath},{filepath.Join(path,"audit.jsonl"),cfg.AuditPath}} { body, err:=os.ReadFile(pair[0]); if err!=nil && !os.IsNotExist(err) { return err }; if err==nil { if err:=os.WriteFile(pair[1], body, 0o644); err!=nil { return err } } }; return audit.Write(ctx,cfg.AuditPath,audit.Event{AgentID:"system",Action:"checkpoint_restore",Target:checkpointID,Outcome:"success",ApprovalRequired:false}) }
func DiffCheckpoints(ctx context.Context, cfg config.Config, a,b string) (map[string]string, error) { rowsA, err:=sqlitepy.Query(ctx,cfg.DBPath,`SELECT snapshot_path FROM checkpoints WHERE id = ?`, a); if err!=nil { return nil, err }; rowsB, err:=sqlitepy.Query(ctx,cfg.DBPath,`SELECT snapshot_path FROM checkpoints WHERE id = ?`, b); if err!=nil { return nil, err }; if len(rowsA)==0 || len(rowsB)==0 { return nil, fmt.Errorf("checkpoint not found") }; return map[string]string{"world.db":diffHash(filepath.Join(sval(rowsA[0]["snapshot_path"]),"world.db"), filepath.Join(sval(rowsB[0]["snapshot_path"]),"world.db")),"graph.db":diffHash(filepath.Join(sval(rowsA[0]["snapshot_path"]),"graph.db"), filepath.Join(sval(rowsB[0]["snapshot_path"]),"graph.db")),"audit.jsonl":diffHash(filepath.Join(sval(rowsA[0]["snapshot_path"]),"audit.jsonl"), filepath.Join(sval(rowsB[0]["snapshot_path"]),"audit.jsonl"))}, nil }
func Replay(ctx context.Context, cfg config.Config, missionID, checkpointID string) (map[string]interface{}, error) { if err:=RestoreCheckpoint(ctx,cfg,checkpointID); err!=nil { return nil, err }; status, err:=Status(ctx,cfg,missionID); if err!=nil { return nil, err }; status["replayed_from"] = checkpointID; _ = audit.Write(ctx,cfg.AuditPath,audit.Event{AgentID:"system",Action:"mission_replay",Target:checkpointID,MissionID:missionID,Outcome:"success",ApprovalRequired:false}); return status,nil }
func AppendTimeline(ctx context.Context, cfg config.Config, missionID, eventType, message string) error { return sqlitepy.ExecParams(ctx,cfg.DBPath,`INSERT INTO timeline_events(id, mission_id, event_type, message, created_at) VALUES (?, ?, ?, ?, ?)`, ids.New("tl"), missionID, eventType, message, time.Now().UTC().Format(time.RFC3339)) }
func Timeline(ctx context.Context, cfg config.Config, missionID string) ([]TimelineEvent, error) { rows, err:=sqlitepy.Query(ctx,cfg.DBPath,`SELECT id, mission_id, event_type, message, created_at FROM timeline_events WHERE mission_id = ? ORDER BY created_at ASC`, missionID); if err!=nil { return nil, err }; out:=make([]TimelineEvent,0,len(rows)); for _, row := range rows { out=append(out, TimelineEvent{ID:sval(row["id"]),MissionID:sval(row["mission_id"]),EventType:sval(row["event_type"]),Message:sval(row["message"]),CreatedAt:sval(row["created_at"])}) }; return out,nil }
func MaybeGenerateAmendment(ctx context.Context, cfg config.Config, agentID string) (string, error) { rows, err:=sqlitepy.Query(ctx,cfg.DBPath,`SELECT COUNT(*) AS failures FROM artifact_checks ac JOIN artifacts a ON a.id = ac.artifact_id WHERE a.origin_agent = ? AND ac.check_type = 'citation_review' AND ac.status = 'failed'`, agentID); if err!=nil { return "", err }; if len(rows)==0 || intVal(rows[0]["failures"])<3 { return "", nil }; path:=filepath.Join(cfg.AgentsPath, agentID, "amendments", ids.New("amendment")+".md"); if err:=os.MkdirAll(filepath.Dir(path),0o755); err!=nil { return "", err }; body:=[]byte("# Handbook Amendment Suggestion\n\n- Tighten citation rules after repeated citation failures.\n"); if err:=os.WriteFile(path, body, 0o644); err!=nil { return "", err }; if err:=sqlitepy.ExecParams(ctx,cfg.DBPath,`INSERT INTO handbook_amendments(id, agent_id, reason, path, created_at) VALUES (?, ?, ?, ?, ?)`, ids.New("hamd"), agentID, "three citation failures", path, time.Now().UTC().Format(time.RFC3339)); err!=nil { return "", err }; _ = audit.Write(ctx,cfg.AuditPath,audit.Event{AgentID:"system",Action:"handbook_amendment_generate",Target:path,Outcome:"success",ApprovalRequired:false}); return path,nil }
func RecordUsage(ctx context.Context, cfg config.Config, missionID, agentID, provider string, tokens int, cost float64) error { if err:=sqlitepy.ExecParams(ctx,cfg.DBPath,`INSERT INTO token_usage(id, mission_id, agent_id, provider, tokens, cost, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)`, ids.New("tok"), missionID, agentID, provider, tokens, cost, time.Now().UTC().Format(time.RFC3339)); err!=nil { return err }; return audit.Write(ctx,cfg.AuditPath,audit.Event{AgentID:defaultAgentID(agentID,"budget"),Action:"budget_record",Target:provider,MissionID:missionID,Outcome:"success",ApprovalRequired:false}) }
func defaultRoomID(ctx context.Context, dbPath string) (string, error) { rows, err:=sqlitepy.Query(ctx,dbPath,`SELECT id FROM rooms ORDER BY id ASC LIMIT 1`); if err!=nil { return "", err }; if len(rows)==0 { return "", fmt.Errorf("no room available") }; return sval(rows[0]["id"]), nil }
func diffHash(a,b string) string { return fileHash(a)+":"+fileHash(b) }
func fileHash(path string) string { body, err:=os.ReadFile(path); if err!=nil { return "missing" }; sum:=sha256.Sum256(body); return hex.EncodeToString(sum[:]) }
func sval(v interface{}) string { return fmt.Sprintf("%v", v) }
func intVal(v interface{}) int { var n int; fmt.Sscanf(fmt.Sprintf("%v", v), "%d", &n); return n }
func defaultAgentID(value, fallback string) string { if strings.TrimSpace(value)=="" { return fallback }; return value }
