package missions

import (
	"context"
	"os"
	"strings"
	"testing"

	"github.com/stizzfer36-del/UCLAW/internal/artifacts"
	"github.com/stizzfer36-del/UCLAW/internal/config"
	"github.com/stizzfer36-del/UCLAW/internal/testingx"
	"github.com/stizzfer36-del/UCLAW/internal/world"
)

func setup(t *testing.T) config.Config { t.Helper(); testingx.TempHome(t); cfg, err:=config.Load(); if err!=nil { t.Fatal(err) }; if err:=config.EnsureLayout(cfg); err!=nil { t.Fatal(err) }; if _, _, err:=world.Init(context.Background(), cfg); err!=nil { t.Fatal(err) }; return cfg }
func TestMissionBlockedWhenCitationFails(t *testing.T) { cfg:=setup(t); m, err:=Start(context.Background(), cfg, "mission", "user", "dev"); if err!=nil { t.Fatal(err) }; file:=cfg.Home+"/artifact.txt"; _=os.WriteFile(file, []byte("x"), 0o644); art, _:=artifacts.Create(context.Background(), cfg, ".", artifacts.CreateRequest{Title:"a", Type:"doc", Path:file, OriginAgent:"builder", MissionID:m.ID, ClaimCount:5, Sources:[]artifacts.Source{{Type:"url", Ref:"https://example.com", CitedBy:"builder"}}}); checks, err:=artifacts.RunChecks(context.Background(), cfg, art.ID, "verifier", "", cfg.Home); if err!=nil { t.Fatal(err) }; failed:=false; for _, check := range checks { if check.Type=="citation_review" && check.Status=="failed" { failed=true } }; if !failed { t.Fatal("expected citation failure") }; if err:=UpdateStatus(context.Background(), cfg, m.ID, "blocked"); err!=nil { t.Fatal(err) }; status, _:=Status(context.Background(), cfg, m.ID); if status["mission"].(map[string]interface{})["status"] != "blocked" { t.Fatalf("expected blocked mission, got %+v", status) } }
func TestCheckpointRoundTrip(t *testing.T) { cfg:=setup(t); m, _:=Start(context.Background(), cfg, "mission", "user", "dev"); cp, err:=SaveCheckpoint(context.Background(), cfg, m.ID, "manual"); if err!=nil { t.Fatal(err) }; if err:=RestoreCheckpoint(context.Background(), cfg, cp.ID); err!=nil { t.Fatal(err) }; list, _:=ListCheckpoints(context.Background(), cfg, m.ID); if len(list)==0 { t.Fatal("expected checkpoint") } }
func TestMissionReplayProducesSameArtifact(t *testing.T) { cfg:=setup(t); m, _:=Start(context.Background(), cfg, "mission", "user", "dev"); file:=cfg.Home+"/artifact.txt"; _=os.WriteFile(file, []byte("x"), 0o644); art, _:=artifacts.Create(context.Background(), cfg, ".", artifacts.CreateRequest{Title:"a", Type:"doc", Path:file, OriginAgent:"builder", MissionID:m.ID, ClaimCount:1, Sources:[]artifacts.Source{{Type:"url", Ref:"https://example.com", CitedBy:"builder"}}}); cp, _:=SaveCheckpoint(context.Background(), cfg, m.ID, "after-artifact"); status, err:=Replay(context.Background(), cfg, m.ID, cp.ID); if err!=nil { t.Fatal(err) }; arts:=status["artifacts"].([]artifacts.Artifact); if len(arts)==0 || arts[0].ID != art.ID { t.Fatalf("expected same artifact after replay, got %+v", arts) } }
func TestHandbookAmendmentAfterThreeCitationFailures(t *testing.T) { cfg:=setup(t); m, _:=Start(context.Background(), cfg, "mission", "user", "dev"); for i:=0; i<3; i++ { file:=cfg.Home+"/artifact-"+string(rune('a'+i))+".txt"; _=os.WriteFile(file, []byte("x"), 0o644); art, _:=artifacts.Create(context.Background(), cfg, ".", artifacts.CreateRequest{Title:"a", Type:"doc", Path:file, OriginAgent:"builder", MissionID:m.ID, ClaimCount:5, Sources:[]artifacts.Source{{Type:"url", Ref:"https://example.com", CitedBy:"builder"}}}); _, _ = artifacts.RunChecks(context.Background(), cfg, art.ID, "verifier", "", cfg.Home) }; path, err:=MaybeGenerateAmendment(context.Background(), cfg, "builder"); if err!=nil { t.Fatal(err) }; if path=="" { t.Fatal("expected amendment path") } }
func TestMissionLifecycleWritesAuditEvents(t *testing.T) { cfg:=setup(t); m, err:=Start(context.Background(), cfg, "mission", "user", "dev"); if err!=nil { t.Fatal(err) }; if err:=UpdateStatus(context.Background(), cfg, m.ID, "active"); err!=nil { t.Fatal(err) }; body, err:=os.ReadFile(cfg.AuditPath); if err!=nil { t.Fatal(err) }; if !strings.Contains(string(body), "mission_start") || !strings.Contains(string(body), "mission_status_update") || !strings.Contains(string(body), "checkpoint_save") { t.Fatalf("expected mission audit events, got %s", string(body)) } }
